#!/bin/bash

# Script for installing initial development environment
# Only one argument is allowed: --os=macos (for the moment only macOS is supported)

# Print right emoji for OS, it accepts only one argument, the OS
# Example: print_os_emoji macos
print_os_emoji() {
    if [ "$1" == "macos" ]; then
        echo "🍎"
    fi
}

# Make sure --os= option is set ( e.g. --os=macos )
os_option=$(echo "$@" | grep -o "\-\-os=[a-z]*" | cut -d "=" -f 2)
if [ -z "$os_option" ]; then
    echo ""
    echo "🚨・No --os= option set. Exiting..."
    echo ""
    exit 1
fi
echo ""
echo "💻・OS: $os_option $(print_os_emoji $os_option)"
echo ""

# Check if gum is installed
if ! command -v gum &> /dev/null
then
    echo "🍬・Gum could not be found. Installing..."
    if [ "$os_option" == "macos" ]; then
        brew install gum
    fi
    echo ""
    echo "Done 🪇"
    echo ""
else
    echo "🍬・Gum is already installed. Skipping..."
    echo ""
    echo "Done 🪇"
    echo ""
fi

# Create python virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo "🐍・Python virtual environment does not exist. Creating..."
    gum spin --spinner monkey --title "Creating virtual environment" -- python3 -m venv venv
    echo ""
    echo "Done 🪇"
    echo ""
else
    echo "🐍・Python virtual environment already exists. Skipping..."
    echo ""
    echo "Done 🪇"
    echo ""
fi

# Check if Make is installed
if ! command -v make &> /dev/null
then
    echo "🛠・Make could not be found. Installing..."
    if [ "$os_option" == "macos" ]; then
        gum spin --spinner monkey --title "Creating virtual environment" --brew install make
    fi
    echo ""
    echo "Done 🪇"
    echo ""
else
    echo "🛠・Make is already installed. Skipping..."
    echo ""
    echo "Done 🪇"
    echo ""
fi
